### TRAER FORO COMPLETO
GET http://localhost:3000/api/foro

### CREAR NUEVA ENTRADA EN EL FORO
POST http://localhost:3000/api/foro
Content-Type: application/json

{
    "title": "nuevo titulo",
    "content": "nuevo contenido",
    "image": "www.url.com"
}

### MODIFICAR UN POST
PUT http://localhost:3000/api/foro/1
Content-Type: application/json

{
    "title": "nuevo titulo",
    "content": "nuevo contenido",
    "image": "www.url.com"
}

### ELIMINA ENTRADA DEL FORO
DELETE http://localhost:3000/api/foro/1